;[BATCON.CTL]
;
; This control file will build the GALAXY batch controller for a
; DECsystem-10 or DECSYSTEM-20.  In the following list of files,
; a (10) indicates the file is required for a TOPS-10 BATCON and
; a (20) for a TOPS-20 BATCON.
;
; Sources:	BATCON.MAC	BATCTL.MAC	BATLOG.MAC	BATMAC.MAC
;		BATPTY.MAC	BATUSR.MAC
;
; Input:	GLXLIB.REL	GLXMAC.UNV	MONSYM.UNV(20)	MNTMAC.UNV(10)
;		MNTPAR.REL(10)	OPRPAR.REL	ORNMAC.UNV	QSRMAC.UNV
;		UUOSYM.UNV(10)
;
; Output:	BATCON.EXE
.GOTO TOPS10
@GOTO TOPS20
TOPS10::
.SET WATCH VERSION
.ASSIGN DEC SYS
.ASSIGN DEC REL
.ASSIGN DEC UNV

.DIRECT /CHECK /SLOW -
*BATCON.MAC, BATCTL.MAC, BATLOG.MAC, BATMAC.MAC, -
*BATPTY.MAC, BATUSR.MAC

.COMPILE/COMPILE BATMAC.MAC
.COMPILE/COMPILE BATCON.MAC
.COMPILE/COMPILE BATCTL.MAC
.COMPILE/COMPILE BATLOG.MAC
.COMPILE/COMPILE BATPTY.MAC
.COMPILE/COMPILE BATUSR.MAC

.R LINK
*BATCON/SAVE = /LOCALS /SYMSEG:LOW /SEGMENT:LOW -
*BATCON, BATCTL, BATLOG, BATPTY, BATUSR -
*/GO

.DIRECT /CHECK /SLOW BATCON.EXE

.PLEASE	BATCON Assembly Successful
.NOERROR
.DEASSIGN SYS
.SUBMIT GALAXY = /MODIFY /DEPEND:-1
.GOTO END

%CERR:: .GOTO ERROR
%ERR::  .GOTO ERROR
%TERR:: .GOTO ERROR

ERROR:: .PLEASE Error during BATCON assembly
.GOTO END
TOPS20::
@DEFINE REL: DEC:
@DEFINE UNV: DEC:

@VDIRECTORY -
@BATCON.MAC, BATCTL.MAC, BATLOG.MAC, BATMAC.MAC, -
@BATPTY.MAC, BATUSR.MAC,
@CHECKSUM SEQUENTIAL
@

@COMPILE/COMPILE BATMAC.MAC
@COMPILE/COMPILE BATCON.MAC
@COMPILE/COMPILE BATCTL.MAC
@COMPILE/COMPILE BATLOG.MAC
@COMPILE/COMPILE BATPTY.MAC
@COMPILE/COMPILE BATUSR.MAC

@R LINK
*BATCON/SAVE = /LOCALS /SYMSEG:LOW /SEGMENT:LOW -
*BATCON, BATCTL, BATLOG, BATPTY, BATUSR -
*/GO

@VDIRECTORY BATCON.EXE,
@CHECKSUM SEQUENTIAL
@

@PLEASE	BATCON Assembly Successful
@NOERROR
@MODIFY BATCH GALAXY /DEPEND:-1
@GOTO END

%ERR::  @GOTO ERROR
%TERR:: @GOTO ERROR

ERROR:: @PLEASE Error during BATCON assembly

END::
%FIN::
;[End of BATCON.CTL]
