;[LPTSPL.CTL]
;
; This control file will build the GALAXY line printer spooler for a
; DECsystem-10 or DECSYSTEM-20.  In the following list of files,
; a (10) indicates the file is required for a TOPS-10 LPTSPL and
; a (20) for a TOPS-20 LPTSPL.
;
; Sources:	LPTMAC.MAC	LPTSPL.MAC	LPTL03.MAC
;		LPTD60.MAC	LPTL01.MAC	LPTLP5.MAC
;
; Input:	ACTSYM.UNV	D60JSY.REL	D60UNV.UNV	GLXLIB.REL
;		GLXMAC.UNV	MONSYM.UNV(20)	ORNMAC.UNV	QSRMAC.UNV
;		UUOSYM.UNV(10)
;
; Output:	LPTSPL.EXE
.GOTO TOPS10
@GOTO TOPS20
TOPS10::
.SET WATCH VERSION
.ASSIGN DEC SYS
.ASSIGN DEC REL
.ASSIGN DEC UNV

.DIRECT /CHECK /SLOW LPTMAC.MAC,LPTSPL.MAC,LPTD60.MAC,LPTL01.MAC,LPTL03.MAC,LPTLP5.MAC

.COMPILE/COMPILE LPTMAC.MAC
.COMPILE/COMPILE LPTSPL.MAC
.COMPILE/COMPILE @DRIVRS.CCL

.R LINK
*LPTSPL/SAVE = /LOCALS /SYMSEG:LOW /SEGMENT:LOW LPTSPL /GO

.DIRECT /CHECK /SLOW LPTSPL.EXE

.PLEASE	LPTSPL Assembly Successful
.NOERROR
.DEASSIGN SYS
.SUBMIT GALAXY = /MODIFY /DEPEND:-1
.GOTO END

%CERR:: .GOTO ERROR
%ERR::  .GOTO ERROR
%TERR:: .GOTO ERROR

ERROR:: .PLEASE Error during LPTSPL assembly
.GOTO END
TOPS20::
@DEFINE REL: DEC:
@DEFINE UNV: DEC:

@VDIRECTORY LPTSPL.MAC,
@CHECKSUM SEQUENTIAL
@

@COMPILE/COMPILE LPTSPL.MAC

@R LINK
*LPTSPL/SAVE = /LOCALS /SYMSEG:LOW /SEGMENT:LOW -
*LPTSPL, D60JSY -
*/GO

@VDIRECTORY LPTSPL.EXE,
@CHECKSUM SEQUENTIAL
@

@PLEASE	LPTSPL Assembly Successful
@NOERROR
@MODIFY BATCH GALAXY /DEPEND:-1
@GOTO END

%ERR::  @GOTO ERROR
%TERR:: @GOTO ERROR

ERROR:: @PLEASE Error during LPTSPL assembly

END::
%FIN::
;[End of LPTSPL.CTL]
