! FOR TOPS10 DO A "JUMP 407" AND FOR TOPS20 DO A "JUMP 71"
SET CON MAI
!	PLEASE NOTE .... CONSOLE IS COLLECTING KL STATUS THIS
!	PROCESS WILL TAKE ABOUT 2 MINUTES .....>  PLEASE WAIT
SET OUT LOG
W VER!		PROTOCOL TIMEOUT ERROR.CMD V 15-50.1 15 Jan 86
WHAT HARDWARE
FX 10
!		CI/NI MAY TRASH FREAD'S... BEWARE
FREAD 100:177
SAVE PC
E REG;E KL
E VMA;E VMAH
E 0:17
REP 10;FX 12;E PC;E 1
FX 11
CLE OUT LOG
!			SNAPSHOT DONE
