.MAKE C.P11
*IOURNNM=31
*.LIST ME,MEB
*.MACRO NODE MNAME
*	MNAME	<BIGLST>
*.ENDM
*.NLIST MEB,ME
*FT.87S=1			;ASSEMBLE AS AN DN87S
*MSGMAX=596.			;HANDLE LARGER MESSAGES
*NGHMAX=8.			;UP TO EIGHT NEIGHBORS FOR EACH NODE
*SCBMAX=32.			;UP TO THIRTY-TWO NODES IN NETWORK
*DQN=1				;ASSEMBLE WITH ONE DQ11
*DMCN=1				;ASSEMBLE WITH ONE DMC11
*DUPN=1				;ASSEMBLE WITH ONE DUP11
*FT.DCP=4			;IDENTIFY VARIATION OF DECNET COMPATIBLE PORT
*.MACRO NSPLST			;DEFINE DECNET LINES
*	DCP4LN	2,<<OBJTSK,20>>,20,KL2102,110.,KL1026,26
*.ENDM
*DEBUG=-1
*FTDGUTS=1			;"DONT GIVE UP THE SHIP"
*FT.TSK=1			;INCLUDE TASK CODE
*FTECHO=1			;WANT TSK: SUPPORT
*    ECHON=2			;TWO ECHO TASKS
*CDRN=1				;ONE CARD READER
*LP11N=1			;ONE LINEPRINTER
*PLTN=1				;ONE PLOTTER
*PTPN=1				;ONE PAPER TAPE PUNCH
*PTRN=1				;ONE PAPER TAPE READER
*FT.PFH=1			;SUPPORT "PREFERRED" HOST SELECTION
*    CTYPFH=10			;CTY PREFERS HOST 10
*    TTYPFH=26			;TTY PREFERS HOST 26
*FT.RNN=1			;SUPPORT "RESTRICTED" HOST SELECTION
*    DDPRNN=26			;ALLOW DDPS TO GO ONLY TO HOST 26
;
;		*** Async line configuration sample for "BIGLST" ***
;
;	This configuration shows how to generate various types of async
;	lines, for both DH11 and DZ11 controllers.
;
*FT.CTY=1			;FORCE SUPPORT OF CTY
*FTDH11=1			;FORCE DH11 SUPPORT
*FTDZ11=1			;FORCE DZ11 SUPPORT
*FTDM11=1			;FORCE DM11 DATASET CONTROL FOR DH11
*FTDN11=1			;FORCE DN11 DIALOUT SUPPORT
*    DN11N=2			; WITH TWO CONTROLLERS
*
*.MACRO DHCNFG			;DEFINE DH11 LINE USAGE
*AHPTPN=1			;NUMBER OF DH PTP DDCMP LINES
*AHRDAN=1			;NUMBER OF DH ASCII RDX LINES
*AHTTYN=10-AHPTPN-AHRDAN	;NUMBER OF DH ASCII TERMINALS
*DHSET	4,PTP,9600.,9600.	;DH LINE 4 IS PTP DDCMP @ 9600
*DHSET	5,RDA,4800.,4800.	;DH LINE 5 IS RDA AT 4800
*TD=0						;START WITH TTY0
*TDEF	TD,<<RS,9600.>,<XS,9600.>>		;TTY0 IS 9600 BAUD
*TDEF	TD,<<RS,300.>,<XS,300.>>		;TTY1 IS 300 BAUD
*TDEF	TD,<<ABD>>				;TTY2 IS AUTOBAUD NON-DATASET
*TDEF	TD,<<RNN,26>,<RS,1200.>,<XS,1200.>>	;TTY3 RESTRICTED TO HOST 26
*TDEF	TD,<<DSL>,<801,0>,<RS,300.>,<XS,300.>>	;TTY4 IS 801 LINE 0 AT 300
*TDEF	TD,<<DSL>,<801,4>,<RS,1200.>,<XS,1200.>>;TTY5 IS 801 LINE 4 AT 1200
*						;NOTE: TTYS ARE ON DH
*						; LINES 0, 1, 2, 3, 6, AND 7
*DHUSE	AHTTYN,AHPTPN,0,0,0,AHRDAN
*.ENDM
*
*.MACRO DZCNFG			;DEFINE DZ11 LINE USAGE
*AZPTPN=1			;NUMBER OF DZ PTP DDCMP LINES
*AZRDAN=1			;NUMBER OF DZ ASCII RDX LINES
*AZTTYN=10-AZPTPN-AZRDAN	;NUMBER OF DZ ASCII TERMINALS
*DZSET	0,PTP,9600.,9600.	;DZ LINE 0 IS PTP DDCMP @ 9600
*DZSET	1,RDA,4800.,4800.	;DZ LINE 1 IS RDA AT 4800
*						;CONTINUE AFTER DH11 WITH TTY6
*TDEF	TD,<<DSL>,<PFH,10>>			;TTY6 IS DATASET PREFERS 10
*TDEF	TD,<<DSL>,<PFH,10>>			;TTY7 IS DATASET PREFERS 10
*TDEF	TD,<<DSL>,<PFH,10>>			;TTY10 IS DATASET PREFERS 10
*TDEF	TD,<<DSL>,<PFH,26>>			;TTY11 IS DATASET PREFERS 26
*TDEF	TD,<<DSL>,<PFH,26>>			;TTY12 IS DATASET PREFERS 26
*TDEF	TD,<<DSL>,<PFH,26>>			;TTY13 IS DATASET PREFERS 26
*						;NOTE: TTYS ARE ON DZ
*						; LINES 2, 3, 4, 5, 6, AND 7
*DZUSE	AZTTYN,AZPTPN,0,0,0,AZRDAN
*.ENDM
*12I
*EX
.R MACDLX
DN87,DN87/CRF=C,S,MACROS,DDT,DNCNFG,DNCOMM,DNNCL,DNDCP4,DNDEV,DNDCMP,DNDTE,DNCDDQ,DNCDUP,DNCDMC,DNTTY,DNRDA,DNDH11,DNDZ11,DNDN11,DNCTAB,DNLPT,DNCRD,DNPTP,DNPTR,DNPLT,DNTSK,TSKTST,DNTRCE,DNDBG,DNLBLK,CHK11
.IF (ERROR)
.R DDT11
*DN87.LST/SYMBOL:2500
.SAVE DN87
.DELETE C.P11
