;BUFIO.CTL   %003  CREATE AND RUN BUFIO.SCP WHICH RUNS
; BUFIO TO TEST BUFFERED I/O FOR VM
;DONALEEN TRAFTON/DKT/SML   4 AUG 77
;
.GOTO SKIP
SCP::
!;;BUFIO.SCP - SCRIPT TO RUN BUFIO TO TEST VM BUFFERED I/O  %003
!;;SM LIBMAN      4 AUG 77
!IORFST   ;;RUN AS FAST AS POSSIBLE
LOGIN
4,777#
!Q
TEST#
!XIN
!;;TRY TO RUN VIRTUALLY
!Q
R SETVM
SET WATCH ALL
ASSIGN DSK DEV
!;;RUN WITH BLOCKING I/O FIRST
RUN TST:BUFIO
N
!;;NOW RUN WITH NON-BLOCKING I/O
RUN TST:BUFIO
Y
DELETE *.*
KJOB/D/D
!XOUT
SKIP::
;ABORT IF NOT A VM MONITOR
.R ISIT ;VM
;IF WE GET HERE THIS IS A VM SYSTEM, TRY TO RUN VIRTUALLY
.R SETVM
.IF (ERROR) ;IGNORE
.R TECO				;MAKE THE FILE
=ERBUFIO.CTL
*_SCP::
=0,.K
=EWBUFIO.SCP
=NSKIP::0L
=.,ZKPWEF
;
;END OF SCRIPT FILE; NOW RUN IT
;
.R SCRIPT
*BUFIO
.CONT
*1
*
*BUFIO
*BUFIO
*
*
*
*Y
*N
*Y
.IF (ERROR) .GOTO B
.PLEASE BUFIO SUCCESSFUL
.DELETE BUFIO.WCH
.GOTO A
B::
.PLEASE ERROR RUNNING BUFIO
.PRINT BUFIO.WCH/DISPOSE:DELETE
A::
%FIN:
.NOERROR
.DELETE BUFIO.SCP
