;ENQDEQ.CTL     %005   CREATE AND RUN ENQDEQ.SCP WHICH RUNS
; ENQDEQ TO TEST ENQUE/DEQUE
;DONALEEN TRAFTON/DKT/SML      4 AUG 77
;
.GOTO SKIP
SCP::
!;;ENQDEQ.SCP - SCRIPT TO RUN ENQDEQ TO TEST ENQUE/DEQUE   %005
!;;SM LIBMAN      4 AUG 77
!IORFST   ;;RUN AS FAST AS POSSIBLE
LOGIN
4,777510
!Q
TEST510
!XIN
SET WATCH ALL
;RUN VIRTUALLY IF WE CAN
!Q
R SETVM
RUN TST:ENQDEQ
!;;RUN 5 COPIES
5
!Q
DELETE *.*
KJOB/D/D
!XOUT
SKIP::
;ABORT IF NO ENQ/DEQ
.R ISIT ;ENQDEQ
;IF WE GET HERE WE HAVE ENQ/DEQ
;TRY TO RUN VIRTUALLY
.R SETVM
.IF (ERROR) ;IGNORE
.R TECO				;MAKE THE FILE
=ERENQDEQ.CTL
*_SCP::
=0,.K
=EWENQDEQ.SCP
=NSKIP::0L
=.,ZKPWEF
;
;END OF SCRIPT FILE; NOW RUN 5 COPIES OF IT
;
.R SCRIPT
*ENQDEQ
.CONT
*5
*
*ENQDEQ
*ENQDEQ
*
*
*
*Y
*N
*Y
.IF (ERROR) .GOTO B
.PLEASE ENQDEQ SUCCESSFUL
.DELETE ENQDEQ.WCH
.GOTO A
B::
.PLEASE ERROR RUNNING ENQDEQ
.PRINT ENQDEQ.WCH/DISPOSE:DELETE
A::
%FIN:
.NOERROR
.DELETE ENQDEQ.SCP
