;LOGLOG.CTL  %010    MAKE AND RUN LOGLOG.SCP 10 JOBS, REPEAT COUNT = 5
;TO TEST SIMULTANEOUS LOGIN AND LOGOUT OF MANY JOBS
; TO TUN LOGLOG TYPE:
;	.QUE INP:=LOGLOG/TIME:400/DIS:DEL
;LOGLOG IS USUALLY RUN BY MONTST IN WEEKLY MONITOR TEST
;6 MARCH 73   P WHITE	MODIFIED  4 AUG 77   SM LIBMAN
;
.GOTO SKIP
SCP::
!;; LOGLOG.SCP - SCRIPT TO TEST LOGIN AND LOGOUT - %010
!;;T. HASTINGS/TH/PFC/SML  4 AUG 77
!IORFS;;AS FAST AS POSSIBLE
LOGIN
4,777#
!Q
TEST#
!XIN
SET TTY ALTMODE
!;;RUN IN VM IF POSSIBLE
!Q
R SETVM
MAKE FOO
I	END
}
!L
EX}}
!N
DIR
KJOB/K
!XOUT
SKIP::
;RUN IN VM
.R SETVM
.IF (ERROR)   ;IGNORE
.R TECO
=ERLOGLOG.CTL
*_SCP::
=0,.K
=EWLOGLOG.SCP
=NSKIP::0L
=.,ZKPWEF
;
;RUN THE SCRIPT, 10 JOBS
.R SCRIPT
*LOGLOG
.CONT
*10
*
*LOGLOG
*LOGLOG
*5
*
*
*Y
*N
*Y
.IF (ERROR) .GOTO B
.PLEASE LOGLOG SUCCESSFUL
.DELETE LOGLOG.WCH
.DELETE LOGLOG.SCP
.GOTO A
B::
.PLEASE ERROR RUNNING LOGLOG.SCP
.QUEUE LOGLOG.WCH/DISPOSE:DELETE
A::
%FIN:
.NOERROR
.DELETE LOGLOG.SCP
