;PAGUUO.CTL     %002   CREATE AND RUN PAGUUO.SCP WHICH RUNS
; PAGUUO TO TEST ALL FUNCTIONS OF THE PAGE. UUO.
;DONALEEN TRAFTON/DKT/SML   4 AUG 77
;
.GOTO SKIP
SCP::
!;;PAGUUO.SCP - SCRIPT TO RUN PAGUUO TO TEST PAGE. UUO.  %002
!;;SM LIBMAN      4 AUG 77
!IORFST   ;;RUN AS FAST AS POSSIBLE
LOGIN
4,777#
!Q
TEST#
!XIN
!;;DO NOT RUN SETVM, PAGUUO CONTROLS ITS OWN CORE
SET WATCH ALL
COPY DSK:=TST:HISEG.HGH
RUN TST:PAGUUO
DELETE *.*
KJOB/D/D
!XOUT
SKIP::
;ABORT IF NOT A VM MONITOR
.R ISIT ;VM
;IF WE GET HERE THIS IS A VM SYSTEM, TRY TO RUN VIRTUALLY
.R SETVM
.IF (ERROR) ;IGNORE
.R TECO				;MAKE THE FILE
=ERPAGUUO.CTL
*_SCP::
=0,.K
=EWPAGUUO.SCP
=NSKIP::0L
=.,ZKPWEF
;
;END OF SCRIPT FILE; NOW RUN 5 COPIES OF IT
;
.R SCRIPT
*PAGUUO
.CONT
*5
*
*PAGUUO
*PAGUUO
*
*
*
*Y
*N
*Y
.IF (ERROR) .GOTO B
.PLEASE PAGUUO SUCCESSFUL
.DELETE PAGUUO.WCH
.GOTO A
B::
.PLEASE ERROR RUNNING PAGUUO
.PRINT PAGUUO.WCH/DISPOSE:DELETE
A::
%FIN:
.NOERROR
.DELETE PAGUUO.SCP
