;SHRH1.CTL: %006   BATCH JOB THAT CREATES AND RUNS SCRIPT SHRH1.SCP
;THIS JOB IS RUN AT THE SAME TIME AS SHRH2.CTL WHICH CREATES
;AND RUNS SHRH2.SCP.  TWO BATCH STREAMS MUST BE RUNNING. THE TWO BATCH
;JOBS SYNCHRONIZE BY WAITING FOR FILES TO APPEAR IN THEIR COMMON
;DSK AREA.  THE SCRIPTS TEST VARYING LOW CORE SIZE WHILE SHARING A
;HIGH SEGMENT.  4 AUG 77   P WHITE/SML
;
;CREATE WAITX2 PROGRAM WHICH SLEEPS UNTIL FILE SHRH2.XXX IS MADE
;ON DSK BY SHRH2.CTL
;
.GOTO SKIP
WAITT::
	MLON
START:	INIT	1,0
	SIXBIT	/DSK/
	0,,0
	JRST	SLP

	LOOKUP	1,[SIXBIT /SHRH2/
		   SIXBIT /XXX/
		   0
		   0]
	JRST	SLP1

	EXIT

SLP:	MOVEI	1,1
	JRST	.+2
SLP1:	MOVEI	1,2
	MOVEI	2,2	;;SLEEP FOR 2 SEC OCTAL
	SLEEP	2,
	JRST	START
	END	START
SCP::
!;;SEE IF SYSTEM WILL TURN PINK %006
!IORFS
LOGIN
4,777#
!Q
TEST#
!0CXIN
!;;LET'S SEE IF WE CAN RUN IN VM
!Q
R SETVM
!Q
DEL *.*
MAKE SHRH1.MAC
I	TITLE SHRH1
	SUBTTL R.S.T./BBN
	EXTERN .JBSYM
BEG:	CALLI 0
	MOVEI 1,NAMBLK
	CALLI 1,40	;GETSEG
	  HALT .
	CALLI 1,23
	MOVEM 1,STARTT
	TSC 1,1
	TRO 1,1
LUP:	MOVE 2,1
	LSH 1,1
	ADD 1,2
	HRLZS 2
	ADDB 1,2
	MULI 2,40
	LSH 2,12
	HLRO 3,.JBSYM
	MOVNS 3
	ADD 3,.JBSYM
	ADDI 2,(3)
	CALLI 2,11
	JFCL
	CALLI 10,23
	SUB 10,STARTT
	SKIPGE 10
	ADD 10,[EXP ^^D60000*^^D60*^^D24]
	CAMG 10,[EXP ^^D60000*^^D5]
	JRST LUP
	CALLI 12

NAMBLK:	SIXBIT /SYS/
	SIXBIT /PIP/
	0
	0
	0
	0

STARTT:	0

	END BEG
!L
EX
!N
EXECUTE SHRH1
DEL *.*
KJOB/K
!XOUT
SKIP::
;RUN VIRTUALLY
.R SETVM
.IF (ERROR)    ;IGNORE
.R TECO
=ERSHRH1.CTL
*_WAITT::
=0,.K
=EWWAITX2.MAC
=NSCP::0L
=.,ZKPWEF
.R TECO
=ERSHRH1.CTL
*_SCP::
=0,.K
=EWSHRH1.SCP
=NSKIP::0L
=.,ZKPWEF
;
;LOAD AND SAVE WAITX2 PROGRAM
.LOAD WAITX2/COMPILE
.SAVE DSK:WAITX2
;
;MAKE FILE SHRH1.XXX TO WAKE UP JOB SHRH2.CTL.  THEN SLEEP UNTIL THAT
;JOB HAS CREATED FILE SHRH2.XXX
;
.MAKE SHRH1.XXX
*ISTART RUNNING SHRH2.SCP NOW
=EX
.EXECUTE WAITX2
;
;SHRH2.XXX FOUND,  RUN SHRH1.SCP
;
.R SCRIPT
*SHRH1
.CONT
*2
*
*SHRH1
*SHRH1
*
*
*
*Y
*N
*Y
.IF (ERROR) .GOTO B
.DELETE SHRH1.WCH
.GOTO A
B:
.QUEUE SHRH1.WCH/DISPOSE:DELETE
A:
%FIN:
.NOERROR
.DELETE SHRH1.XXX
.DELETE SHRH1.SCP
.DELETE SHRH1.XXX
.DELETE WAITX2.*
.QUEUE INP:TTUSR1=/MODIFY/DEPEND:-1
.QUEUE INP:TTUSR2=/MODIFY/DEPEND:-1
