;SHRH2.CTL: %007   BATCH JOB THAT CREATES AND RUNS SCRIPT SHRH2.SCP
;THIS JOB IS RUN AT THE SAME TIME AS SHRH1.CTL WHICH CREATES
;AND RUNS SHRH1.SCP.  TWO BATCH STREAMS MUST BE RUNNING. THE TWO BATCH
;JOBS SYNCHRONIZE BY WAITING FOR FILES TO APPEAR IN THEIR COMMON
;DSK AREA.  THE SCRIPTS TEST VARYING LOW CORE SIZE WHILE SHARING A
;HIGH SEGMENT.  4 AUG 77   P WHITE/SML
;
;CREATE WAITX1 PROGRAM WHICH SLEEPS UNTIL FILE SHRH1.XXX IS MADE
;ON DSK BY SHRH1.CTL
;
.GOTO SKIP
WAITT::
	MLON
START:	INIT	1,0
	SIXBIT	/DSK/
	0,,0
	JRST	SLP

	LOOKUP	1,[SIXBIT /SHRH1/
		   SIXBIT /XXX/
		   0
		   0]
	JRST	SLP1

	EXIT

SLP:	MOVEI	1,1
	JRST	.+2
SLP1:	MOVEI	1,2
	MOVEI	2,2	;;SLEEP FOR 2 SEC OCTAL
	SLEEP	2,
	JRST	START
	END	START
SCP::
!;;SEE IF SYSTEM WILL TURN PINK %006
!IORFS
LOGIN
4,777#
!Q
TEST#
!0CXIN
!;;TRY TO RUN IN VM
!Q
R SETVM
!Q
DEL *.*
MAKE SHRH2.MAC
I	TITLE SHRH2
	SUBTTL R.S.T./BBN
	EXTERN .JBSYM
BEG:	CALLI 0
	MOVEI 1,NAMBLK
	CALLI 1,40	;GETSEG
	  HALT .
	CALLI 1,23
	MOVEM 1,STARTT
	TSC 1,1
	TRO 1,1
LUP:	MOVE 2,1
	LSH 1,1
	ADD 1,2
	HRLZS 2
	ADDB 1,2
	MULI 2,40
	LSH 2,12
	HLRO 3,.JBSYM
	MOVNS 3
	ADD 3,.JBSYM
	ADDI 2,(3)
	CALLI 2,11
	JFCL
	CALLI 10,23
	SUB 10,STARTT
	SKIPGE 10
	ADD 10,[EXP ^^D60000*^^D60*^^D24]
	CAMG 10,[EXP ^^D60000*^^D5]
	JRST LUP
	CALLI 12

NAMBLK:	SIXBIT /SYS/
	SIXBIT /MACRO/
	0
	0
	0
	0

STARTT:	0

	END BEG
!L
EX
!N
EXECUTE SHRH2
DEL *.*
KJOB/K
!XOUT
SKIP::
;RUN VIRTUALLY
.R SETVM
.IF (ERROR)   ;IGNORE
.R TECO
=ERSHRH2.CTL
*_WAITT::
=0,.K
=EWWAITX1.MAC
=NSCP::0L
=.,ZKPWEF
.R TECO
=ERSHRH2.CTL
*_SCP::
=0,.K
=EWSHRH2.SCP
=NSKIP::0L
=.,ZKPWEF
;
;LOAD AND SAVE WAITX1 PROGRAM
.LOAD WAITX1/COMPILE
.SAVE DSK:WAITX1
;
;MAKE FILE SHRH2.XXX TO WAKE UP JOB SHRH1.CTL.  THEN SLEEP UNTIL THAT
;JOB HAS CREATED FILE SHRH1.XXX
;
.MAKE SHRH2.XXX
*ISTART RUNNING SHRH1.SCP NOW
=EX
.EXECUTE WAITX1
;
;SHRH1.XXX FOUND.   RUN SHRH2.SCP
;
.R SCRIPT
*SHRH2
.CONT
*2
*
*SHRH2
*SHRH2
*
*
*
*Y
*N
*Y
.IF (ERROR) .GOTO B
.DELETE SHRH2.WCH
.GOTO A
B:
.QUEUE SHRH2.WCH/DISPOSE:DELETE
A:
%FIN:
.NOERROR
.DELETE SHRH2.XXX
.DELETE SHRH2.SCP
.DELETE SHRH2.XXX
.DELETE WAITX1.*
.QUEUE INP:TTUSR1=/MODIFY/DEPEND:-1
.QUEUE INP:TTUSR2=/MODIFY/DEPEND:-1
