;TECMAC.CTL  %010   MAKE AND RUN TECMAC.SCP WHICH SIMULATES A LOAD OF
;USERS DOING TECO, MACRO, AND FORTRAN, WITH 2 SEC RESPONSE TIME, 
;QUICK USERS, SMALL PROGRAMS.  THE SCRIPT REPEATS ITSELF 2 TIMES. 10
;COPIES ARE RUN, STAGGERED. TO RUN TECMAC TYPE:
;	SUBMIT TECMAC/TIME:700,/DIS:DEL
;TECMAC IS USUALLY RUN BY MONTST.CTL IN WEEKLY MONITOR TEST
;P WHITE/SML	 4 AUG 77  SM LIBMAN
;
.GOTO SKIP
SCP::
!;; TECMAC.SCP - LEVEL D TECO/MACRO TEST SCRIPT    %010
!;;CM FLETCHER/PFC/PW/SML       4 AUG 77
!;;FOR 6.03 MONITOR
! 500I 100O  2000R 2000F
!2T;;DO THIS 2 TIMES
! 10000S ;;STAGGER TIME
!;; ASSUME 2SEC RESPONSE AND QUICK USER
LOG
4,777#
!Q
TEST#
!VXIN
!;;TRY TO RUN IN VM
!Q
R SETVM
R PIP
DSK:/Z_
^C
SET WATCH VERSION
SET TTY ALTMODE     ; TECO NEEDS ALTMODE CONVERSION
MAKE MODULO
IC	ROUTINE TO TYPE IN TWO INTEGERS N1,N2
C	AND TO TYPE OUT N1 MODULO N2.

1	TYPE 5
5	FORMAT(' TYPE N1 AND N2'//)
	ACCEPT 10,N1,N2
10	FORMAT(2I)
	M=MOD(N1,N2)
	TYPE 20,N1,N2,M
20	FORMAT(1X,I5,' MOD 'I5,' IS 'I5//)
	GO TO 1
	END
!L
}}EX}}
!N
MAKE MACSUB.MAC
I	;MOD SUBROUTINE WITH STANDARD FORTRAN CALLING SEQUENCE
	;FORTRAN STATEMT M=MOD(N1,N2)
	;RESULTS IN CALL TO MOD IN THE FORM
	;	JSA 16,MOD
	;	ARG 0,N1
	;	ARG 0,N2
	;THUS UPOL ENTRY TO MOD,AC16 POINTS TO N1
	;THE REMAINDER OR "MOD" FUNCTION IS RETURNED IN AC0
	;AS THE RESULT OF DIVIDING N1 (IN AC17) BY N2.


ENTRY MOD	;ENTRY POINT FOR LOADER
MOD:	0
	MOVEM 17,SAV17	;SAVE AC17
	MOVE 17,@(16)	;PICKP UP N1
	IDIV 17,@(16)	;DEVIDE BY N2 (REMAINDER IN AC0)
	MOVE 17,SAV17	;RESTORE AC17
	JRA 16,2(16)	;RETURN TO CALLING PROGRAM
SAV177:	0
	END
!L
}}
!N
JSSTATEM}IEN}0LT}}
SSAV177}-1D0LT}}
!L
EX}}
!N
EXECUTE  MODULO,MACSUB.MAC
10 3
12 8
^C
TECO MACSUB.MAC
!L
JSIDIV 17,@}I1}0LT}}
EX}}
!N
EXEC MODULO,MACSUB.MAC
10 3
12 8
^C
DEL *.*
KJOB/K
!XOUT
SKIP::
;DO THIS IN VM IF WE CAN
.R SETVM
.IF (ERROR)  ;IGNORE
.R TECO
=ERTECMAC.CTL
*_SCP::
=0,.K
=EWTECMAC.SCP
=NSKIP::0L
=.,ZKPWEF
;
;END OF FILE TECMAC.SCP.  RUN 10 JOBS.
;
;RUN AS FAST AS POSSIBLE FOR MONTST.
.R SCRIPT
*TECMAC
.CONT
*10
*
*TECMAC
*TECMAC
*2
*0
*
*Y
*N
*Y
.IF (ERROR) .GOTO B
.PLEASE TECMAC SUCCESSFUL
.DELETE TECMAC.WCH
.DELETE TECMAC.SCP
.GOTO A
B::
.PLEASE ERROR RUNNING TECMAC.SCP
.QUEUE TECMAC.WCH/DISPOSE:DELETE
A::
%FIN:
.NOERROR
.DELETE TECMAC.SCP
