;TTUSR1.CTL  %007   MAKE TTUSER.SCP AND RUN 14 JOBS.  THIS JOB
;IS RUN TOGETHER WITH TTUSR2.CTL WHICH RUNS 14 MORE JOBS OF TTUSER.SCP.
;THIS JOB WAITS FOR FILE TTUSR2.XXX TO BE CREATED ON DSK BY 
;TTUSR2.CTL, THEN MAKES AND RUNS THE SCRIPT.  TTUSR2.CTL WAITS FOR
;TTUSER.SCP
;4 AUG 77    P WHITE/SML
;
;WAIT FOR TTUSR2.CTL TO MAKE FILE TTUSR2.XXX
;
.GOTO MAKE
WAITT::
	MLON
START:	INIT	1,0
	SIXBIT	/DSK/
	0,,0
	JRST	SLP

	LOOKUP	1,[SIXBIT /TTUSR2/
		   SIXBIT /XXX/
		   0
		   0]
	JRST	SLP1

	EXIT

SLP:	MOVEI	1,1
	JRST	.+2
SLP1:	MOVEI	1,2
	MOVEI	2,3	;;SLEEP FOR 3 SEC OCTAL
	SLEEP	2,
	JRST	START

	END	START
MAKE::
;RUN IN VM IF POSSIBLE
.R SETVM
.IF (ERROR)   ;IGNORE
.R TECO
=ERTTUSR1.CTL
*_WAITT::
=0,.K
=EWWAITTT.MAC
=NMAKE::0L
=.,ZKPWEF
.EXECUTE WAITTT
; CREATE THE SCRIPT
;
.GOTO SKIP
SCP::
!;;TTUSER.SCP  SCRIPT TO USE UP TTY CHUNKS  %007
!;;P WHITE/SML   4 AUG 77
!IOFRS
LOGIN
4,777#
!Q
TEST#
!XIN
!;; RUN IN VM IF WE CAN
!Q
R SETVM
R BASIC
NEW
TTUSER
10	FOR X=1 TO 1000
20	PRINT X
30	NEXT X
50	END
RUN
SYSTEM
^C
R PIP
DSK:/Z_
^C
KJOB/K
!XOUT
SKIP::
.R TECO
=ERTTUSR1.CTL
*_SCP::
=0,.K
=EWTTUSER.SCP
=NSKIP::0L
=.,ZKPWEF
;
;END OF FILE TTUSER.SCP.  RUN 14 JOBS.  TTUSR2.CTL WILL START 14 MORE
;
.R SCRIPT
*TTUSER
.CONT
*14
*
*TTUSR1
*TTUSR1
*
*
*
*Y
*N
*Y
.IF (ERROR)  ;WCH FILE IS TOO LONG TO LIST
%FIN:
.NOERROR
.DELETE TTUSER.SCP
