;UPDATE.CTL  %011   RUN 5 COPIES OF UPDATE PROGRAM WHICH TESTS
;UPDATING DISK FILES.  UPDATE.EXE MUST BE IN TST.  TO RUN, TYPE:
;	.SUB=UPDATE/TIME:100,/DIS:DEL
;UPDATE IS USUALLY RUN BY MONTST.CTL IN WEEKLY MONITOR TEST
;6 MAR 72   P WHITE	24 MAR 80  SM LIBMAN
;
.GOTO SKIP
SCP::
!;; UPDATE.SCP - SCRIPT TO TEST UPDATE - %006
!;; D. BLACK/PFC/PW/SML   24 MAR 80
!IORFS;;RUN AS FAST AS POSSIBLE
LOGIN
4,777#
!Q
TEST#
!XIN
R PIP
DSK:/Z_
^C
RUN TST:UPDATE
^C
SYSTAT
KJOB/K
!XOUT
SKIP::
.R TECO
=ERUPDATE.CTL
*_SCP::
=0,.K
=EWUPDATE.SCP
=NSKIP::0L
=.,ZKPWEF
;
;END OF FILE UPDATE.SCP; NOW RUN IT
;
.R SCRIPT
*UPDATE
.CONT
*5
*
*UPDATE
*UPDATE
*
*
*
*Y
*N
*Y
.IF (ERROR) .GOTO B
.PLEASE UPDATE SUCCESSFUL
.DELETE UPDATE.WCH
.GOTO A
B::
.PLEASE ERROR RUNNING UPDATE
.QUEUE UPDATE.WCH/DISPOSE:DELETE
A::
%FIN:
.DELETE UPDATE.SCP
.QUEUE INP:SHRH1=/MODIFY/DEPEND:-1
.QUEUE INP:SHRH2=/MODIFY/DEPEND:-1
