;[PULSAR.CTL]
;
; This control file will build the GALAXY disk/magtape/DECtape processor
; for a DECsystem-10.
;
; Sources:	PLRQUO.MAC	PLRDSK.MAC	PLRDSP.MAC	PLRDTA.MAC
;		PLRINI.MAC	PLRLBP.MAC	PLRMAC.MAC	PLROPR.MAC
;		PLRT10.MAC	PLRTAP.MAC	PULSAR.MAC
;
; Input:	GLXLIB.REL	GLXMAC.UNV	QSRMAC.UNV 	ORNMAC.UNV
;		UFDPRM.UNV	UFDSET.REL	UUOSYM.UNV
;
; Output:	PULSAR.EXE
.SET WATCH VERSION
.ASSIGN DEC SYS
.ASSIGN DEC REL
.ASSIGN DEC UNV

.DIRECT /CHECK /SLOW -
*QUOPRM.MAC, QUOTAB.MAC, -
*PLRQUO.MAC, PLRDSK.MAC, PLRDSP.MAC, PLRDTA.MAC, -
*PLRINI.MAC, PLRLBP.MAC, PLRMAC.MAC, PLROPR.MAC, -
*PLRT10.MAC, PLRTAP.MAC, PULSAR.MAC

.COMPILE/COMPILE PLRMAC.MAC
.COMPILE/COMPILE QUOPRM.MAC
.COMPILE/COMPILE PLRDSK.MAC
.COMPILE/COMPILE PLRDSP.MAC
.COMPILE/COMPILE PLRDTA.MAC
.COMPILE/COMPILE PLRINI.MAC
.COMPILE/COMPILE PLRLBP.MAC
.COMPILE/COMPILE PLROPR.MAC
.COMPILE/COMPILE PLRQUO.MAC
.COMPILE/COMPILE PLRT10.MAC
.COMPILE/COMPILE PLRTAP.MAC
.COMPILE/COMPILE PULSAR.MAC
.COMPILE/COMPILE QUOTAB.MAC

.R LINK
*PULSAR/SAVE = /LOCALS /SYMSEG:LOW /SEGMENT:LOW -
*PLRDSK, PLRDSP, PLRDTA, PLRINI, PLRLBP, -
*PLROPR, PLRQUO, PLRT10, PLRTAP, PULSAR, -
*UFDSET, ACTLIB/SEARCH -
*/GO

.DIRECT /CHECK /SLOW PULSAR.EXE

.PLEASE	PULSAR Assembly Successful
.NOERROR
.DEASSIGN SYS
.SUBMIT GALAXY = /MODIFY /DEPEND:-1
.GOTO END

%CERR:: .GOTO ERROR
%ERR::  .GOTO ERROR
%TERR:: .GOTO ERROR

ERROR:: .PLEASE Error during PULSAR assembly

END::
%FIN::
;[End of PULSAR.CTL]
