;[OPERAT.CTL]
;
; This control file will build the GALAXY operator controller for a
; DECsystem-10 or DECSYSTEM-20.  In the following list of files,
; a (10) indicates the file is required for a TOPS-10 OPR/ORION and
; a (20) for a TOPS-20 OPR/ORION.
;
; Sources:	OPR.MAC   	OPRCMD.MAC	OPRERR.MAC	OPRLOG.MAC
;		OPRNET.MAC	OPRPAR.MAC	OPRQSR.MAC	ORNMAC.MAC
;		ORION.MAC
;
;		CNFHDW.MAC(10)	CNFORN.MAC(10)	CNFTAB.MAC(10)
;		LCPTAB.MAC	LCPORN.MAC
;		QUOPRM.MAC(10)	QUOTAB.MAC(10)
;
; Input:	ACTSYM.UNV	GLXLIB.REL	GLXMAC.UNV	MONSYM.UNV(20)
;		QSRMAC.UNV	UUOSYM.UNV(10)	NCPTAB.REL
;
; Output:	OPR.EXE   	OPRPAR.REL	ORION.EXE	ORNMAC.UNV
.GOTO TOPS10
@GOTO TOPS20
TOPS10::
.SET WATCH VERSION
.ASSIGN DEC SYS
.ASSIGN DEC REL
.ASSIGN DEC UNV

.DIRECT /CHECK /SLOW -
*OPR.MAC,    OPRCMD.MAC, OPRERR.MAC, OPRLOG.MAC, -
*OPRNET.MAC, OPRPAR.MAC, OPRQSR.MAC, ORNMAC.MAC, -
*ORION.MAC, -
*CNFHDW.MAC, CNFORN.MAC, CNFTAB.MAC, LCPTAB.MAC, LCPORN.MAC, -
*QUOPRM.MAC, QUOTAB.MAC

;ADD A DLIST SWITCH TO MAKE A LISTING FOR A BLISSABLE ORNMAC
.COMPILE/COMPILE /DLIST ORNMAC.MAC
.COMPILE/COMPILE OPR.MAC
.COMPILE/COMPILE OPRCMD.MAC
.COMPILE/COMPILE OPRERR.MAC
.COMPILE/COMPILE OPRLOG.MAC
.COMPILE/COMPILE OPRNET.MAC
.COMPILE/COMPILE OPRPAR.MAC
.COMPILE/COMPILE OPRQSR.MAC
.COMPILE/COMPILE ORION.MAC
.COMPILE/COMPILE CNFHDW.MAC
.COMPILE/COMPILE CNFORN.MAC
.COMPILE/COMPILE CNFTAB.MAC
.COMPILE/COMPILE LCPORN.MAC
.COMPILE/COMPILE LCPTAB.MAC
.COMPILE/COMPILE QUOPRM.MAC
.COMPILE/COMPILE QUOTAB.MAC

LINK::
.R LINK
*OPR/SAVE = /LOCALS /SYMSEG:LOW /SEGMENT:LOW OPR, OPRPAR, OPRCMD /GO

.R LINK
*ORION/SAVE = /LOCALS /SYMSEG:LOW /SEGMENT:LOW -
*ORION, OPRQSR, OPRPAR, OPRLOG, OPRNET, OPRERR /GO

.ERROR %

;CHECK TO SEE IF WE CAN MAKE A BLISSABLE ORNMAC

.DIR SYS:MONINT.EXE
.IF (ERROR) .GOTO DIR
.DIR SYS:BLISS.EXE
.IF (ERROR) .GOTO DIR

.R MONINT
*ORNMAC

.R BLISS
*ORNMAC=ORNMAC/LIBRARY

DIR::

.DIRECT /CHECK /SLOW -
*OPR.EXE, OPRPAR.REL, ORION.EXE, ORNMAC.UNV

.PLEASE	OPERAT Assembly Successful
.NOERROR
;.DEASSIGN SYS
.SUBMIT GALAXY = /MODIFY /DEPEND:-1
.GOTO END

%CERR:: .GOTO ERROR
%ERR::  .GOTO ERROR
%TERR:: .GOTO ERROR

ERROR:: .PLEASE Error during OPERAT assembly
.GOTO END
TOPS20::
@DEFINE REL: DSK:
@DEFINE UNV: DSK:

@VDIRECTORY -
@OPR.MAC,    OPRCMD.MAC, OPRERR.MAC, OPRLOG.MAC, -
@OPRNET.MAC, OPRPAR.MAC, OPRQSR.MAC, ORNMAC.MAC, -
@ORION.MAC

@COMPILE/COMPILE ORNMAC.MAC
@COMPILE/COMPILE OPR.MAC
@COMPILE/COMPILE OPRCMD.MAC
@COMPILE/COMPILE OPRERR.MAC
@COMPILE/COMPILE OPRLOG.MAC
@COMPILE/COMPILE OPRNET.MAC
@COMPILE/COMPILE OPRPAR.MAC
@COMPILE/COMPILE OPRQSR.MAC
@COMPILE/COMPILE ORION.MAC

@R LINK
*OPR/SAVE = OPR, OPRPAR/SEGMENT:LOW, OPRCMD /GO

@R LINK
*ORION/SAVE = ORION, OPRQSR, OPRPAR/SEGMENT:LOW, OPRLOG, OPRNET, OPRERR /GO

@VDIRECTORY -
@OPR.EXE, OPRPAR.REL, ORION.EXE, ORNMAC.UNV
@CHECKSUM SEQUENTIAL
@

@PLEASE	OPERAT Assembly Successful
@NOERROR
@MODIFY BATCH GALAXY /DEPEND:-1
@GOTO END

%ERR::  @GOTO ERROR
%TERR:: @GOTO ERROR

ERROR:: @PLEASE Error during OPERAT assembly

END::
%FIN::
;[End of OPERAT.CTL]
