.R FORTRA
*TATTLE,TATTLE/C=TATTLE
.R MACRO
*TATSUB,TATSUB/C=TATSUB
*SNOOPY,SNOOPY/C=SNOOPY
.R LINK
*SNOOPY/GO
.SAVE SNOOPY
.R LINK
*TATTLE,TATSUB/GO
.SAVE TATTLE
.DELETE SNOOPY.REL,TATTLE.REL,TATSUB.REL
.R CREF
*=SNOOPY
*=TATTLE
*=TATSUB
