title	finger -- simple finger server.
search	jobdat, uuosym, macten

p1==11
p2==12
p3==13
p4==14

data:	byte (4)  11, 12,  0,  0,  0, 15, 11,  4, 15
	byte (4)  11,  4, 15, 11,  4, 15, 11,  4, 15
	byte (4)  11,  4, 15, 11,  4, 15,  3,  0,  0
	byte (4)   0,  2,  4,  2,  0,  0,  0, 15,  2
	byte (4)   4,  1,  4,  1,  4,  2,  0,  0,  0
	byte (4)  15,  2,  4,  1,  4,  1,  4,  1,  4
	byte (4)  15,  2,  4,  1,  4,  1,  4,  1,  4
	byte (4)  14, 13,  0,  5,  4,  0,  6,  0,  4
	byte (4)   1,  4, 14, 12,  2,  4,  4, 10, 10
	byte (4)   4,  1,  4, 14, 12,  3,  2, 11,  4
	byte (4)   0,  4, 14, 12,  3,  2, 11, 13, 14
	byte (4)  12,  3,  2, 11, 13, 14, 11,  5,  1
	byte (4)  11, 13, 14, 11,  6,  0, 11, 12, 14
	byte (4)  11, 12,  2, 14, 12, 12,  0, 14, 13
	byte (4)  11, 16, 14, 15, 11, 12, 14,  0,  0

finger:	jfcl
	reset
	movei	p1,getchr
	move	p2,[point 4,data]
loop:	jsp	p1,(p1)
	 jrst	done
	outchr	p3
	jrst	loop

done:	monrt.
	jrst	finger

getchr:	ildb	p4,p2
	trzn	p4,10
	 jrst	getc.2
	lsh	p4,4
	ildb	p3,p2
	add	p4,p3
getc.2:	trzn	p4,100
	 jrst	getc.4
	movei	p3,15
	jsp	p1,1(p1)
	movei	p3,12
	jsp	p1,1(p1)
	jumpe	p4,(p1)
getc.4:	jumpe	p4,getc.6
getc.5:	movei	p3," "
	jsp	p1,1(p1)
	sojg	p4,getc.5
getc.6:	movei	p3,"*"
	jsp	p1,1(p1)
	jrst	getchr

end	finger
