

SUBTTL	GALCNF	Created by GALGEN Version 5(2124) at  4-Aug-3 13:21:53

	UNIVERSAL GALCNF
	.DIRECT	.NOBIN


	DEFINE XP (SYM,VAL) <
	SYM==:VAL>

	G.%GLN==500002124		;STANDARD VERSION FOR GALGEN
	G.GVER==5		;GALAXY VERSION NUMBER

	RADIX 5+5


	FTUUOS==-1			;-1 IF TOPS 10 ELSE 0
	FTJSYS==0			;-1 IF TOPS 20 ELSE 0


; 
; In the following dialog, all questions are of the form:
; 
;   text of question (list or range of answers) [default answer]

; 
; The line starts with the actual text of the question.  Following
; the question is a description  of the possible answers  enclosed
; in parentheses.  This description might be a range of numbers, a
; list of  keywords, or  a  textual description.   Following  this
; description is the default answer, enclosed in square  brackets.
; The default will be assumed if you only press the RETURN key.

; 
; You have the  choice of carrying  on a LONG  dialog in which  an
; explanation of  each question  is provided  automatically, or  a
; SHORT dialog in which it is  assumed that you are familiar  with
; the GALAXY generation procedure.  In either case, you can always
; obtain the help text by typing  a question mark (?) in  response
; to any question.

; 
; 
; Answer the  following  question with  either  LONG (for  a  long
; dialog) or SHORT (for a short one).  Simply pressing the  RETURN
; key will imply SHORT.
; 

;Dialog Length (SHORT,LONG) [SHORT] l

SUBTTL	Administrative Controls and Parameters


;        Administrative Controls and Parameters       
;        -------------- -------- --- ----------       
; 

; 
; The  questions  in  this   section  determine  absolute   GALAXY
; parameters, which  cannot  be  overridden by  user  or  operator
; commands.

	XP	G.OLOG,-1

; 
;  
; The system logs all operator interactions in a disk file in  the
; spooling area.  Your answer to the following question  specifies
; the name to be used for this file.
; 

;Operator log filename (3-6 Characters) [OPERAT] 


DEFINE G$$LGN <	X	OPERAT>

; 
; 
; You have the option  of maintaining a  backup master queue  file
; which may be used in the unlikely event that the primary  master
; queue file is destroyed.
; 

;Do you want redundant master queue file (YES,NO) [NO] 


	XP	FTRQUE,0

; 
; 
; Any  permanantly  mounted  structure  may be used for the master
; queues.  The structure that is first in the system  search  list
; is preferred.
; 

;File structure to use for master queue (3-6 Characters) [SSL] 


	XP	G.QSTR,'SSL   '

; 
; 
; Users can  specify  a  priority for  their  batch  and  spooling
; requests with the  /PRIORITY switch.  The  allowable values  for
; this parameter range  between 1  (representing lowest  priority)
; and 63 (representing the highest).  The following two  questions
; relate to this switch.  The first question requests the  maximum
; priority which may be specified by a non-privileged user. 
; 

;Maximum priority non-privileged users may specify (1-63) [20] 


	XP	G.SPRI,20

; 
; 
; You may specify the value to be used if the user does not specify
; a /PRIORITY switch.  This value must be between 1 and the maximum
; that you specified in the previous question.
; 

;Default for /PRIORITY on batch and spooling requests (1-63) [10] 


	XP	G.DPRI,10
SUBTTL	[SYSTEM]INFO Parameters


;               [SYSTEM]INFO Parameters               
;               ------------ ----------               
; 

; 
; This section allows you to set any currently defined [SYSTEM]INFO
; control parameters.

	XP	FTINFO,-1	;Enable [SYSTEM]INFO support

; 
; 
; The [SYSTEM]INFO facility, which allows users to manipulate PIDs
; for IPCF communication by symbolic names, is now part of QUASAR.
; While  [SYSTEM]INFO  normally  limits  the  maximum length  of a
; symbolic  PID  name  via the  GETTAB item %IPMPL (maximum packet
; length),  you have the option  of  specifying the maximum length
; of a PID name allowable at all.
; 

;Maximum length of a PID name (29-79 Characters) [39] 


	XP	SZ.INF,39
SUBTTL	Applications


;                     Applications                    
;                     ------------                    
; 

; 
; The following section determines which optional applications
; you wish to run on your system.  These applications will be 
; accesible through OPR, the operator interface program.  
; 

; 
; 
; GALAXY supports by default the CATALOG, CONFIG, and QUOTA applications.
; If you wish to run additional applications (such as NCP), answer YES.
; 

;Do you wish to run optional applications? (YES,NO) [YES] 


; 
; The LAT Control Protocol (LCP) commands allow the operator or system
; administrator to control various aspects of Local Area Transport (LAT)
; service, and to display status and parameter settings information.
; 
; The LCP command subset is required if your monitor is built with
; Ethernet LAT terminal access enabled.
; 

;Include the LAT Control Protocol (LCP) commands?  (YES,NO) [YES] 


; 
; The Network Control Protocol (NCP) commands allow the system administrator
; to perform various DECnet network management functions.
; 
; The NCP command subset is required if you are running DECnet-10.
; 

;Include the DECnet Network Control Protocol (NCP) commands?  (YES,NO) [YES] 


; 
; 
; You can include installation-developed applications with your answers
; to the following questions.
; 

;Do you wish to run any installation-developed applications? (YES,NO) [NO] 


DEFINE G$$ATB <

X	<CATALOG>,0,CATTAB,

X	<CONFIG>,1,CNFTAB,CNFORN

X	<LCP>,2,LCPTAB,LCPORN

X	<NCP>,3,NCPTAB,

X	<QUOTA>,4,QUOTAB,

> ; END OF G$$ATB
SUBTTL	Batch Job Defaults


;                  Batch Job Defaults                 
;                  ----- --- --------                 
; 

; 
; The questions in this section are used to define default  values
; for  the various options that a user can specify when submitting
; a batch job.

; 
; 
; The  batch  user can specify a maximum runtime for his batch job
; using the /TIME switch.  If he does not specify this switch  the
; following default will be used:
; 

;Default batch job runtime limit (5-9999 seconds) [300] 


	XP	G.ITIM,300

; 
;  
; Every batch  job has  maximum limits  for each  type of  spooled
; output.  These  limits  can  be  set  by  the  batch  user  with
; appropriate switches to the SUBMIT command.  If the user doesn't
; specify these switches, the following defaults will be used:
; 

;Line printer output limit (0-9999 pages) [200] 


	XP	G.ILPT,200

;Card punch output limit (0-9999 cards) [1000] 


	XP	G.ICDP,1000

;Paper tape punch output limit (0-5000 feet) [200] 


	XP	G.IPTP,200

;Plotter output limit (0-5000 minutes) [30] 


	XP	G.IPLT,30

; 
;  
; The user can specify whether or not the batch log file should be
; printed after the job terminates by using the /OUTPUT switch  to
; the SUBMIT command.  The action  is specified by: LOG to  always
; print the log file, NOLOG to never print the log file, and ERROR
; to print the log  file only if the  job ended with an  unhandled
; error.  If the user doesn't  specify this switch, the  following
; value will be used.
; 

;Default for SUBMIT/OUTPUT (LOG,NOLOG,ERROR) [LOG] 


	XP	G.ILOG,2

; 
; 
; The  system  provides  for the enforcement of a maximum physical
; memory limit on batch jobs.  The  user  can  specify  a  maximum
; memory  parameter  and  if  any  program attempts to exceed this
; limit, the batch job goes virtual.
; 

;Should memory limits be enforced (YES,NO) [YES] 


; 
; 
; The  user  can specify a maximum memory limit by using the /CORE
; switch.  If this switch  is  not  specified  by  the  user,  the
; following default will be used.
; 

;Memory limit (24-16384 pages) [512] 


	XP	G.ICOR,512	;CORE LIMITS
SUBTTL	Line Printer Defaults and Parameters


;         Line Printer Defaults and Parameters        
;         ---- ------- -------- --- ----------        
; 

; 
; The questions in this section are used to set default values for
; the line printer spooler.

; 
; 
; Job banner pages are printed at  the  beginning  of  each  print
; request.   The  user's  name  and  any /NOTE value is printed on
; them.
; 

;Number of job banner pages (0-5) [2] 0


	XP	G.LBAN,0

; 
; 
; Job  trailer pages are printed at the end of each print request.
; The user's  name  and  any  spooler  checkpoint  information  is
; printed on them.
; 

;Number of job trailer pages (0-5) [2] 0


	XP	G.LTRL,0

; 
; 
; File header pages are printed before  each file or copy in  each
; print request.  The file name is printed in BOLD letters on each
; header page.
; 

;Number of file header pages (0-5) [2] 0


	XP	G.LHDR,0

; 
; 
; The user can specify a special form for a print request with the
; /FORMS switch.  If this switch is not  specified  the  following
; default will be used.
; 

;Name for standard output forms (4-6 Characters) [NORMAL] 


	XP	G.DNOR,'NORMAL'

; 
; 
; The number  of  characters  that uniquely  identify  a  form  is
; compared with  the current  form name  to determine  if a  forms
; change is required for a specific user request.
; 

;Number of characters which uniquely identifies form (2-6) [4] 


	XP	G.DNUC,4

; 
; 
; 
; There may  be site specific devices which require special device
; drivers loaded  with  LPTSPL  as needed.  For example,  the LN01
; laser printer requires  the module  LPTL01  in  order for LPTSPL
; to load fonts as requested. 
; 

;Do you want to load any special printer drivers? (YES,NO) [NO] y


; 
; 
; 
; Each device driver must have  its own module  to be  loaded with
; the LPTSPL main module. This module's .REL file must be found on
; the build area when LPTSPL is loaded. 
; 

DEFINE G$$LPT <

	LL	lptl01

	LL	lpttty

> ; End of G$$LPT
SUBTTL	Parameters for MDA


;                  Parameters for MDA                 
;                  ---------- --- ---                 
; 

; 
; The questions  in  this section  are  used to  set  the  default
; parameters for the Mountable Device Allocator (MDA).

; 
; 
; The   following  question  allows  you to  enable  the  deadlock
; avoidance code in  MDA. This  code  prevents jobs  from  waiting
; for  tape or  disk resources that another  job  may already own,
; or that  do not  exist. Enabling  the  deadlock  avoidance  code
; causes MDA  to  use  sligthly  more  CPU  time  to  insure  that
; deadlocks  will  not occur.
; 

;Enable deadlock avoidance? (YES,NO) [YES] 


	XP	G.DEAD,-1	;DEADLOCK AVOIDANCE


	      %TRK7==1			      ; 7 TRACK
	      %TRK9==2			      ; 9 TRACK
	

; 
; 
; You have  the  option of  specifying  which label  type  is  the
; default.
;                              NOTE:
; Label type USER-EOT will allow a user program to see the end  of
; tape condition on an UNLABELED tape only.  All other label types
; will  cause  the  user  to  block  at  end  of  tape  while  MDA
; automatically  expands  the  volume  set.  In this case the user
; program will NOT see end of tape.  
; 

;Default tape label type (ANSI,BYPASS,IBM,USER-EOT,UNLABELED) [USER-EOT] 


	XP	DEFLBT,10

; 
; 
; You have the option of  specifying the default density at  which
; tapes are read and written.
; 

;Default 9-track tape density (200,556,800,1600,6250) [1600] 


	XP	DEF9TK,4

;Default 7-track tape density (200,556,800) [800] 


	XP	DEF7TK,3

; 
; 
; You have  the option  of specifying  the default  track type  on
; which to mount tapes.
; 

;Default track type (7,9) [9] 


	XP	DEFTRK,%TRK9

; 
; 
; The system  administrator  can  allow  non-privileged  users  to
; bypass label processing.
; 

;Allow bypassing for non-privileged users? (YES,NO) [NO] 


	XP	NPRTLB,0
SUBTTL	Miscellaneous Defaults and Parameters


;        Miscellaneous Defaults and Parameters        
;        ------------- -------- --- ----------        
; 

; 
; The  questions  in   this  section  refer   to  general   GALAXY
; parameters.

; 
; 
; The following section establishes default bias and disk page  to
; spooler unit conversion factors.
; 

;Do you want the standard limit computation (YES,NO) [YES] 


	XP	G.LPTM,6

	XP	G.LPTD,8

	XP	G.CDPM,33

	XP	G.CDPD,4

	XP	G.PLTM,7

	XP	G.PLTD,100

	XP	G.PTPM,7

	XP	G.PTPD,4

; 
; 
; The default action to be taken when output exceeds the specified
; limit for an output spooler may  be to ABORT the job and  ignore
; all remaining output, ASK the operator what to do, or PROCEED to
; finish processing the job.
; 

;Default output-limit-exceeded action (ABORT,ASK,PROCEED) [ASK] 


	XP	G.FLEA,2

; 
; 
; If file access between network nodes is to be done, each FAL -
; file access listener - stream needs a network type  associated
; with it. The 2  network types supported are ANF-10 and DECnet.
; 

;Default network-type for FAL streams (ANF-10,DECnet) [ANF-10] 


	XP	G.FNTY,1

; 
; 
; Galaxy-10 spoolers (object processors) are now grouped into three
; categories  and  are  started (logged-in and  run) by  QUASAR  at
; different times depending  on which  category they fall into. The
; three categories and their corresponding characteristics are:
; 

; 
; %ONCE  - "fired up" by  QUASAR  after QUASAR starts ORION, PULSAR
;          and CATLOG).  The spooler will never logout on its own.
; 

; 
; %STCMD - "fired up" by QUASAR when an OPR START command is issued
;          for a stream controlled by the spooler. The spooler will
;          logout when all streams under its control are shut down.
; 

; 
; %DEMND - "fired up" by QUASAR  when a job is in a queue that  can
;          be serviced by one  of the spooler's job streams.  These
;          "demand"  spoolers  will  logout  after  "n"  minutes of
;          idleness.  You will be prompted below to  define a value
;          for "n".
; 

; 
; The PRCDAT macro in QSRMAC.MAC defines the category to which each
; supported object processor/spooler belongs.
; 

;Number of minutes "demand" spoolers tolerate idleness (5-60) [10] 


	XP	G.IMIN,10

	XP	FTDN60,-1	;Always include DN60 support

	XP	FTFTS,0		;No FTS support

	XP	FTDQS,0		;No DQS support

	XP	FTRJE,0		;No DN200 support

	XP	FTFACT,0	;FACT file support off

; 
; 
; 
; Your site may wish to include additional symbols and values which
; are different from  Digital's standard ones.  By specifying these
; values here,  you may  further tailor  GALAXY  to your particular
; installation.
; 

;Do you wish to enter any site specific paramters? (YES,NO) [NO] 



	END
