;[PLEASE.CTL]
;
; This control file will build the GALAXY commumications program for a
; DECsystem-10 or DECSYSTEM-20.  In the following list of files,
; a (10) indicates the file is required for a TOPS-10 PLEASE and
; a (20) for a TOPS-20 PLEASE.
;
; Sources:	PLEASE.MAC
;
; Input:	GLXLIB.REL	GLXMAC.UNV	MONSYM.UNV(20)	UUOSYM.UNV(10)
;
; Output:	PLEASE.EXE
.GOTO TOPS10
@GOTO TOPS20
TOPS10::
.SET WATCH VERSION
.ASSIGN DEC SYS
.ASSIGN DEC REL
.ASSIGN DEC UNV

.DIRECT /CHECK /SLOW PLEASE.MAC

.COMPILE/COMPILE PLEASE.MAC

.R LINK
*PLEASE/SAVE = /LOCALS /SYMSEG:LOW /SEGMENT:LOW -
*GLXLIB/EXCLUDE:GLXINI, PLEASE -
*/GO

.DIRECT /CHECK /SLOW PLEASE.EXE

.PLEASE	PLEASE Assembly Successful
.NOERROR
.DEASSIGN SYS
.SUBMIT GALAXY = /MODIFY /DEPEND:-1
.GOTO END

%CERR:: .GOTO ERROR
%ERR::  .GOTO ERROR
%TERR:: .GOTO ERROR

ERROR:: .PLEASE Error during PLEASE assembly
.GOTO END
TOPS20::
@DEFINE REL: DEC:
@DEFINE UNV: DEC:

@VDIRECTORY PLEASE.MAC,
@CHECKSUM SEQUENTIAL
@

@COMPILE/COMPILE PLEASE.MAC

@R LINK
*PLEASE/SAVE = /LOCALS /SYMSEG:LOW /SEGMENT:LOW -
*GLXLIB/EXCLUDE:GLXINI, PLEASE -
*/GO

@VDIRECTORY PLEASE.EXE,
@CHECKSUM SEQUENTIAL
@

@PLEASE	PLEASE Assembly Successful
@NOERROR
@MODIFY BATCH GALAXY /DEPEND:-1
@GOTO END

%ERR::  @GOTO ERROR
%TERR:: @GOTO ERROR

ERROR:: @PLEASE Error during PLEASE assembly

END::
%FIN::
;[End of PLEASE.CTL]
