;[MOUNT.CTL]
;
; This control file will build the GALAXY user mount interface for a
; DECsystem-10.
;
; Sources:	MNTMAC.MAC	MNTPAR.MAC	MOUNT.MAC
;
; Input:	GLXLIB.REL	GLXMAC.UNV	OPRPAR.REL	ORNMAC.UNV
;		QSRMAC.UNV	UUOSYM.UNV
;
; Output:	MNTMAC.UNV	MNTPAR.REL	MOUNT.EXE
.SET WATCH VERSION
.ASSIGN DEC SYS
.ASSIGN DEC REL
.ASSIGN DEC UNV

.DIRECT /CHECK /SLOW -
*MNTMAC.MAC, MNTPAR.MAC, MOUNT.MAC

.COMPILE/COMPILE MNTMAC.MAC
.COMPILE/COMPILE MNTPAR.MAC
.COMPILE/COMPILE MOUNT.MAC

.R LINK
*MOUNT/SSAVE = /LOCALS /SYMSEG:HIGH -
*REL:GLXLIB/EXCLUDE:GLXINI, MOUNT, MNTPAR, REL:OPRPAR -
*/GO

.DIRECT /CHECK /SLOW -
*MNTMAC.UNV, MNTPAR.REL, MOUNT.EXE

.GOTO END

%CERR:: .GOTO ERROR
%ERR::  .GOTO ERROR
%TERR:: .GOTO ERROR

ERROR:: .PLEASE Error during MOUNT assembly

END::
%FIN::
;[End of MOUNT.CTL]
