;[QMANGR.CTL]
;
; This control file will build the GALAXY user queue-class command
; interface and the MPB/GALAXY interface for a DECsystem-10, and the
; MPB/GALAXY interface for a DECsystem-20.  In the following list of
; files, a (10) indicates the file is required for TOPS-10 and a (20)
; for TOPS-20.
;
; Sources:	QMANGR.MAC	QUENCH.MAC(10)
;
; Input:	GLXMAC.UNV	HELPER.REL(10)	MONSYM.UNV(20)	ORNMAC.UNV
;		QSRMAC.UNV	SCAN.REL(10)	SCNMAC.UNV(10)	WILD.REL(10)
;		UUOSYM.UNV(10)
;
; Output:	QMANGR.EXE	QUEUE.EXE(10)
.GOTO TOPS10
@GOTO TOPS20
TOPS10::
.SET WATCH VERSION
.ASSIGN DEC SYS
.ASSIGN DEC REL
.ASSIGN DEC UNV

.DIRECT /CHECK /SLOW QMANGR.MAC, QUENCH.MAC

.COMPILE/COMPILE QMANGR.MAC
.COMPILE/COMPILE QUENCH.MAC

.R LINK
*QMANGR/SSAVE = /LOCALS /SYMSEG:HIGH QMANGR /GO

.SET WATCH FILES
.R LINK
*QUENCH/SSAVE = /LOCALS /SYMSEG:HIGH QMANGR, QUENCH /GO

.DIRECT /CHECK /SLOW QMANGR.EXE, QUEUE.EXE

.PLEASE	QUENCH/QMANGR Assembly Successful
.NOERROR
.DEASSIGN SYS
.GOTO END

%CERR:: .GOTO ERROR
%ERR::  .GOTO ERROR
%TERR:: .GOTO ERROR

ERROR:: .PLEASE Error during QUEUE assembly
.GOTO END
TOPS20::
@DEFINE REL: DEC:
@DEFINE UNV: DEC:

@VDIRECTORY QMANGR.MAC,
@CHECKSUM SEQUENTIAL
@

@COMPILE/COMPILE QMANGR.MAC

@R LINK
*QMANGR/SAVE = /LOCALS /SYMSEG:HIGH QMANGR /GO

@VDIRECTORY QMANGR.EXE,
@CHECKSUM SEQUENTIAL
@

@PLEASE	QUEUE Assembly Successful
@NOERROR
@MODIFY BATCH GALAXY /DEPEND:-1
@GOTO END

%ERR::  @GOTO ERROR
%TERR:: @GOTO ERROR

ERROR:: @PLEASE Error during QUEUE assembly

END::
%FIN::
;[End of QUEUE.CTL]
