; TRACK.CTL %2  -  CONTROL TO BUILD TRACK.EXE FROM SOURCES
;  TO RUN THIS FILE, .SUBMIT TRACK.CTL
;
; REQUIRED FILES:
; [SELF]
;	TRACK.MAC	;SOURCE PROGRAM
;	TRACK.RNH	;HELP FILE AND EXPLANATION
;	TRK5.RND	;VERSION 4 DOC FILE
;
; OUTPUT FILES:
;	TRACK.EXE OR SAV ;RUNNABLE TRACK PROGRAM
;	TRK5.DOC	;VERSION 4 DOC FILE
;	TRACK.HLP	;HELP FILE
;	TRACK.LST	;CREFFED LISTING FILE



;; NOW COMPILE TRACK, AND LOAD IT

.COMPILE/MACRO/CREF/COMPILE TRACK.MAC

.R LINK
*TRACK/SSAVE=TRACK/GO


%FIN::
;	.PLEASE DONE COMPILING TRACK
