;[CDRIVE.CTL]
;
; This control file will build the GALAXY card reader spooler for a
; DECsystem-10 or DECSYSTEM-20.  In the following list of files,
; a (10) indicates the file is required for a TOPS-10 CDRIVE and
; a (20) for a TOPS-20 CDRIVE.
;
; Sources:	CDRIVE.MAC
;
; Input:	ACTSYM.UNV	D60JSY.REL	D60UNV.UNV	GLXLIB.REL
;		GLXMAC.UNV	MONSYM.UNV(20)	ORNMAC.UNV	QSRMAC.UNV
;		UUOSYM.UNV(10)
;
; Output:	CDRIVE.EXE
.GOTO TOPS10
@GOTO TOPS20
TOPS10::
.SET WATCH VERSION
.ASSIGN DEC SYS
.ASSIGN DEC REL
.ASSIGN DEC UNV

.DIRECT /CHECK /SLOW CDRIVE.MAC

.COMPILE/COMPILE CDRIVE.MAC

.R LINK
*CDRIVE/SAVE = /LOCALS /SYMSEG:LOW /SEGMENT:LOW -
*CDRIVE, REL:D60JSY -
*/GO

.DIRECT /CHECK /SLOW CDRIVE.EXE

.PLEASE	CDRIVE Assembly Successful
.NOERROR
.DEASSIGN SYS
.SUBMIT GALAXY = /MODIFY /DEPEND:-1
.GOTO END

%CERR:: .GOTO ERROR
%ERR::  .GOTO ERROR
%TERR:: .GOTO ERROR

ERROR:: .PLEASE Error during CDRIVE assembly
.GOTO END
TOPS20::
@DEFINE REL: DEC:
@DEFINE UNV: DEC:

@VDIRECTORY CDRIVE.MAC,
@CHECKSUM SEQUENTIAL
@

@COMPILE/COMPILE CDRIVE.MAC

@R LINK
*CDRIVE/SAVE = /LOCALS /SYMSEG:LOW /SEGMENT:LOW -
*CDRIVE, D60JSY -
*/GO

@VDIRECTORY CDRIVE.EXE,
@CHECKSUM SEQUENTIAL
@

@PLEASE	CDRIVE Assembly Successful
@NOERROR
@MODIFY BATCH GALAXY /DEPEND:-1
@GOTO END

%ERR::  @GOTO ERROR
%TERR:: @GOTO ERROR

ERROR:: @PLEASE Error during CDRIVE assembly

END::
%FIN::
;[End of CDRIVE.CTL]
