;[QUASAR.CTL]
;
; This control file will build the GALAXY queue manager for a
; DECsystem-10 or DECSYSTEM-20.  In the following list of files,
; a (10) indicates the file is required for a TOPS-10 QUASAR and
; a (20) for a TOPS-20 QUASAR.
;
; Sources:	QUASAR.MAC	QSRADM.MAC	QSRALC.MAC(10)	QSRDSP.MAC
;		QSRFSS.MAC	QSRIPC.MAC	QSRMAC.MAC	QSRMDA.MAC
;		QSRMEM.MAC	QSRNET.MAC	QSRQUE.MAC	QSRSCH.MAC
;		QSRT10.MAC(10)	QSRT20.MAC(20)	QSRCAT.MAC	QSRINF.MAC
;
; Input:	ACTSYM.UNV	D60JSY.UNV	GALCNF.UNV	GLXLIB.REL
;		GLXMAC.UNV	MONSYM.UNV(20)	ORNMAC.UNV	QSRMAC.UNV
;		UUOSYM.UNV(10)	CATPRM.UNV
;
; Output:	QSRMAC.UNV	QUASAR.EXE
.GOTO TOPS10
@GOTO TOPS20
TOPS10::
.SET WATCH VERSION
.ASSIGN DEC SYS
.ASSIGN DEC REL
.ASSIGN DEC UNV

.DIRECT /CHECK /SLOW -
*QSRADM.MAC, QSRALC.MAC, QSRDSP.MAC, QSRFSS.MAC, -
*QSRIPC.MAC, QSRMAC.MAC, QSRMDA.MAC, QSRMEM.MAC, -
*QSRNET.MAC, QSRQUE.MAC, QSRSCH.MAC, QSRT10.MAC, -
*QUASAR.MAC, QSRCAT.MAC, QSRINF.MAC

.COMPILE/COMPILE QSRMAC.MAC
.COMPILE/COMPILE QSRADM.MAC
.COMPILE/COMPILE QSRALC.MAC
.COMPILE/COMPILE QSRCAT.MAC
.COMPILE/COMPILE QSRDSP.MAC
.COMPILE/COMPILE QSRFSS.MAC
.COMPILE/COMPILE QSRINF.MAC
.COMPILE/COMPILE QSRIPC.MAC
.COMPILE/COMPILE QSRMDA.MAC
.COMPILE/COMPILE QSRMEM.MAC
.COMPILE/COMPILE QSRNET.MAC
.COMPILE/COMPILE QSRQUE.MAC
.COMPILE/COMPILE QSRSCH.MAC
.COMPILE/COMPILE QSRT10.MAC
.COMPILE/COMPILE QUASAR.MAC

LINK::
.R LINK
*QUASAR/SAVE = /LOCALS /SYMSEG:LOW -
*QSRADM, QSRALC, QSRCAT, QSRDSP, QSRFSS, -
*QSRINF, QSRIPC, QSRMDA, QSRMEM, QSRNET, -
*QSRQUE, QSRSCH, QSRT10, QUASAR -
*/GO

.DIRECT /CHECK /SLOW QSRMAC.UNV, QUASAR.EXE

.PLEASE	QUASAR Assembly Successful
.NOERROR
.SUBMIT GALAXY = /MODIFY /DEPEND:-1
.GOTO END

%CERR:: .GOTO ERROR
%ERR::  .GOTO ERROR
%TERR:: .GOTO ERROR

ERROR:: .PLEASE Error during QUASAR assembly
.GOTO END
TOPS20::
@DEFINE REL: DEC:
@DEFINE UNV: DEC:

@VDIRECTORY -
@QSRADM.MAC, QSRDSP.MAC, QSRFSS.MAC, QSRIPC.MAC, -
@QSRMAC.MAC, QSRMDA.MAC, QSRMEM.MAC, QSRNET.MAC, -
@QSRQUE.MAC, QSRSCH.MAC, QSRT20.MAC, QUASAR.MAC,
@CHECKSUM SEQUENTIAL
@

@COMPILE/COMPILE QSRMAC.MAC
@COMPILE/COMPILE QSRADM.MAC
@COMPILE/COMPILE QSRDSP.MAC
@COMPILE/COMPILE QSRFSS.MAC
@COMPILE/COMPILE QSRIPC.MAC
@COMPILE/COMPILE QSRMDA.MAC
@COMPILE/COMPILE QSRMEM.MAC
@COMPILE/COMPILE QSRNET.MAC
@COMPILE/COMPILE QSRQUE.MAC
@COMPILE/COMPILE QSRSCH.MAC
@COMPILE/COMPILE QSRT20.MAC
@COMPILE/COMPILE QUASAR.MAC

@R LINK
*QUASAR/SAVE = /LOCALS /SYMSEG:LOW -
*QSRADM, QSRDSP, QSRFSS, QSRIPC, -
*QSRMDA, QSRMEM, QSRNET, QSRQUE, -
*QSRSCH, QSRT10, QUASAR -
*/GO

@VDIRECTORY QSRMAC.UNV, QUASAR.EXE,
@CHECKSUM SEQUENTIAL
@

@PLEASE	QUASAR Assembly Successful
@NOERROR
@MODIFY BATCH GALAXY /DEPEND:-1
@GOTO END

%ERR::  @GOTO ERROR
%TERR:: @GOTO ERROR

ERROR:: @PLEASE Error during QUASAR assembly

END::
%FIN::
;[End of QUASAR.CTL]
