;[SPROUT.CTL]
;
; This control file will build the GALAXY output device spooler for a
; DECsystem-10 or DECSYSTEM-20.  In the following list of files,
; a (10) indicates the file is required for a TOPS-10 SPROUT and
; a (20) for a TOPS-20 SPROUT.
;
; Sources:	SPROUT.MAC
;
; Input:	ACTSYM.UNV	GLXLIB.REL	GLXMAC.UNV	MONSYM.UNV(20)
;		ORNMAC.UNV	QSRMAC.UNV	UUOSYM.UNV(10)
;
; Output:	SPROUT.EXE
.GOTO TOPS10
@GOTO TOPS20
TOPS10::
.SET WATCH VERSION
.ASSIGN DEC SYS
.ASSIGN DEC REL
.ASSIGN DEC UNV

.DIRECT /CHECK /SLOW SPROUT.MAC

.COMPILE/COMPILE SPROUT.MAC

.R LINK
*SPROUT/SAVE = /LOCALS /SYMSEG:LOW SPROUT /GO

.DIRECT /CHECK /SLOW SPROUT.EXE
.GOTO END

%CERR:: .GOTO ERROR
%ERR::  .GOTO ERROR
%TERR:: .GOTO ERROR

ERROR:: .PLEASE Error during SPROUT assembly
.GOTO END
TOPS20::
@DEFINE REL: DEC:
@DEFINE UNV: DEC:

@VDIRECTORY SPROUT.MAC,
@CHECKSUM SEQUENTIAL
@

@COMPILE/COMPILE SPROUT.MAC

@R LINK
*SPROUT/SAVE = /LOCALS /SYMSEG:LOW SPROUT /GO

@VDIRECTORY SPROUT.EXE,
@CHECKSUM SEQUENTIAL
@

@PLEASE	SPROUT Assembly Successful
@NOERROR
@MODIFY BATCH GALAXY /DEPEND:-1
@GOTO END

%ERR::  @GOTO ERROR
%TERR:: @GOTO ERROR

ERROR:: @PLEASE Error during SPROUT assembly

END::
%FIN::
;[End of SPROUT.CTL]
