
;DC76.CTL -- VERSION 1(1)
;SUBMIT WITH:  .SUBMIT DC76
;
;THIS FILE BUILDS A PDP-11 BINARY WHICH WILL SUPPORT THE DC76
; FRONT END TO THE DECSYSTEM-10.  NO CONFIGURATION DEPENDENT DATA
; IS REQUIRED AS ALL SUCH PARAMETERS ARE SET BY THE PDP-10 BASED
; ON INFORMATION SUPPLIED TO MONGEN.
;
;REQUIRED FILES:
;[10,7] (LATEST RELEASED VERSION)
;	MACDLX.SHR
;[SELF]	DC76.P11
;
;OUTPUT FILES:
;	DC76.BIN
;	DC76.LST
;	DC76.LOG
;
.COP D:(XB)_[10,7]MACDLX.SHR
;RECORD VERSION NUMBERS OF PROGRAMS USED:
.SET WATCH VERSION
.IF (ERROR)  .DIRECT MACDLX.SHR[10,7]/CHECKSUM
;
;FIRST ASSEMBLE THE PDP-11 CODE USING MACDLX
;
.RU MACDLX[10,7]
*DC76.BIN,DC76/CRF=DC76.P11
;
;NOW GENERATE A LISTING (CREF PROGRAM NOT REQUIRED)
;
.PRINT DC76.LST
;
;GET A CHECKSUM DIRECTORY
.DIR DC76 /CHECKSUM
;
;THE FILE DC76.BIN MAY NOW BE LOADED INTO THE DC76 USING BOOT11.
; A TYPICAL INTERATION WOULD BE:
;
;	.R BOOT11
;	FILE:  DC76.BIN/PORT:0
;	PDP-11 LOADING
;	PDP-11 STARTED
;	.
;
;FOR MORE INFORMATION SEE BOOT11 DOCUMENTATION
.PLEASE DC76 DONE
.KJOB/F
;[END OF DC76.CTL]
