SET CON MAI
!	PLEASE NOTE .... CONSOLE IS COLLECTING KL STATUS THIS
!	PROCESS WILL TAKE ABOUT 2 MINUTES .....>  PLEASE WAIT
SET OUT LOG
W VER!			 CRAM.CMD V 15-50.1 15 Jan 86
WHAT HARDWARE
E CRA;E CRL
FREAD 100:177
SAVE PC
E REG;E KL
E VMA;E VMAH
SAVE AC-BLOCK
WHAT AC
CLEAR PAR CRAM
RESET
RESET IO
ST MIC
QSAV 1=1;QSAV 2=2
DE 1=701500 0
DE NE=254000 2
ST 1
ST MIC
QRES 1=1;QRES 2=2
SET PAR CRAM
CLE OUT LOG
!			SNAPSHOT DONE
