SET CON MAI
!	PLEASE NOTE .... CONSOLE IS COLLECTING KL STATUS THIS
!	PROCESS WILL TAKE ABOUT 2 MINUTES .....>  PLEASE WAIT
SET OUT LOG
W VER!			 FMPAR.CMD V 15-50.1 15 Jan 86
WHAT HARDWARE
FREAD 100:177
SAVE PC
E REG;E KL
E REG;E KL
SWEEP
SAVE AC-BLOCK
WHAT AC
CLEAR PAR FM
RESET
RESET IO
ST MIC
QSAV 1=1;QSAV 2=2
DE 1=701500 0
DE NE=254000 2
ST 1
ST MIC
QRES 1=1;QRES 2=2
RESTORE AC
E 0:17
SET PAR FM
CLE OUT LOG
!                               SNAPSHOT DONE

