;[SPRINT.CTL]
;
; This control file will build the GALAXY card reader interpreter for a
; DECsystem-10 or DECSYSTEM-20.  In the following list of files,
; a (10) indicates the file is required for a TOPS-10 SPRINT and
; a (20) for a TOPS-20 SPRINT.
;
; Sources:	SPRINT.MAC
;
; Input:	ACTSYM.UNV	GLXLIB.REL	GLXMAC.UNV	MONSYM.UNV(20)
;		ORNMAC.UNV	QSRMAC.UNV	UUOSYM.UNV(10)
;
; Output:	SPRINT.EXE
.GOTO TOPS10
@GOTO TOPS20
TOPS10::
.SET WATCH VERSION
.ASSIGN DEC SYS
.ASSIGN DEC REL
.ASSIGN DEC UNV

.DIRECT /CHECK /SLOW SPRINT.MAC

.COMPILE/COMPILE SPRINT.MAC

.R LINK
*SPRINT/SAVE = /LOCALS /SYMSEG:LOW SPRINT /GO

.DIRECT /CHECK /SLOW SPRINT.EXE

.PLEASE	SPRINT Assembly Successful
.NOERROR
;.DEASSIGN SYS
.SUBMIT GALAXY = /MODIFY /DEPEND:-1
.GOTO END

%CERR:: .GOTO ERROR
%ERR::  .GOTO ERROR
%TERR:: .GOTO ERROR

ERROR:: .PLEASE Error during SPRINT assembly
.GOTO END
TOPS20::
@DEFINE REL: DEC:
@DEFINE UNV: DEC:

@VDIRECTORY SPRINT.MAC,
@CHECKSUM SEQUENTIAL
@

@COMPILE/COMPILE SPRINT.MAC

@R LINK
*SPRINT/SAVE = /LOCALS /SYMSEG:LOW SPRINT /GO

@VDIRECTORY SPRINT.EXE,
@CHECKSUM SEQUENTIAL
@

@PLEASE	SPRINT Assembly Successful
@NOERROR
@MODIFY BATCH GALAXY /DEPEND:-1
@GOTO END

%ERR::  @GOTO ERROR
%TERR:: @GOTO ERROR

ERROR:: @PLEASE Error during SPRINT assembly

END::
%FIN::
;[End of SPRINT.CTL]
