;[CATLOG.CTL]
;
; This control file will build the GALAXY catalog handler
;  program for a DECsystem-10.
;
; Sources:	CATLOG.MAC	CATTAB.MAC	CATPRM.MAC	CATDEV.MAC
;		CATRMS.MAC
;
; Input:	GLXLIB.REL	GLXMAC.UNV	UUOSYM.UNV
;
; Output:	CATLOG.EXE

.SET WATCH VERSION
.ASSIGN DEC SYS
.ASSIGN DEC REL
.ASSIGN DEC UNV

.DIRECT /CHECK /SLOW CATLOG.MAC, CATPRM.MAC, CATTAB.MAC, CATDEV.MAC, -
*CATRMS.MAC

.COMPILE/COMPIL CATPRM.MAC
.COMPILE/COMPIL CATDEV.MAC
.COMPILE/COMPIL CATLOG.MAC
.COMPILE/COMPIL CATTAB.MAC
.COMPILE/COMPIL CATRMS.MAC
.COMPILE/COMPIL CATCNV.MAC

.R LINK
*CATLOG/SAVE = /LOCALS /SYMSEG:LOW /SEGMENT:LOW -
*CATLOG, CATDEV, CATRMS, REL:RMS -
*/GO

.R LINK
*CATCNV/SAVE = /LOCALS /SYMSEG:LOW /SEGMENT:LOW -
*CATCNV, CATRMS, REL:RMS -
*/GO

.DIRECT /CHECK /SLOW CATLOG.EXE

.PLEASE	CATLOG Assembly Successful
.NOERROR
.DEASSIGN SYS
.SUBMIT GALAXY = /MODIFY /DEPEND:-1
.GOTO END

%CERR:: .GOTO ERROR
%ERR::  .GOTO ERROR
%TERR:: .GOTO ERROR

ERROR:: .PLEASE Error during CATLOG assembly
END::
%FIN::
;[End of CATLOG.CTL]
