;[GLXLIB.CTL]
;
; This control file will build the GALAXY batch controller for a
; DECsystem-10 or DECSYSTEM-20.
;
; Sources:	GLXCOM.MAC	GLXFIL.MAC	GLXFUN.MAC	GLXIPC.MAC
;		GLXINI.MAC	GLXINT.MAC	GLXKBD.MAC	GLXLNK.MAC
;		GLXMAC.MAC	GLXMEM.MAC	GLXOTS.MAC	GLXSCN.MAC
;		GLXTXT.MAC	GLXUTL.MAC	GLXVER.MAC
;
; Input:	GALGEN.MAC	MONSYM.UNV(20)	UUOSYM.UNV(10)
;
; Output:	GLXLIB.EXE	GLXLIB.REL

; Build GLXLIB linkable library
;

.IF (ERROR)
.ASS DEC SYS
.ASS DEC UNV
.ASS DEC REL
.SET WATCH VERSION
.SET WAT FILES

COMPIL::
.COPY GLXPUR.MAC=TTY:
GLXPURE=0

.COMPILE /COMPILE GLXPUR.MAC+GLXVER.MAC+GLXMAC.MAC
.COMPILE /COMPILE GLXINI.MAC
.COMPILE /COMPILE GLXUTL.MAC
.COMPILE /COMPILE GLXCOM.MAC
.COMPILE /COMPILE GLXFIL.MAC
.COMPILE /COMPILE GLXFUN.MAC
.COMPILE /COMPILE GLXINT.MAC
.COMPILE /COMPILE GLXIPC.MAC
.COMPILE /COMPILE GLXKBD.MAC
.COMPILE /COMPILE GLXLNK.MAC
.COMPILE /COMPILE GLXMEM.MAC
.COMPILE /COMPILE GLXOTS.MAC
.COMPILE /COMPILE GLXSCN.MAC
.COMPILE /COMPILE GLXTXT.MAC

.R PIP
*GLXLIB.REL=GLXINI.REL,GLXMAC.REL,GLXUTL.REL,GLXOTS.REL,GLXFUN.REL,GLXCOM.REL,GLXIPC.REL,GLXFIL.REL,GLXTXT.REL,GLXLNK.REL,GLXSCN.REL,GLXKBD.REL,GLXMEM.REL,GLXINT.REL
.R MAKLIB
*GLXLIB.REL=GLXLIB.REL/INDEX/EXIT


; Build GLXLIB Object Time System
;
.COPY GLXPUR.MAC=TTY:
GLXPURE==-1

;MAKE A STRAIGHT LISTING OF GLXMAC FOR THE BLISSABLE STUFF
.COMPILE /COMPILE /DLIST GLXPUR.MAC+GLXVER.MAC+GLXMAC.MAC
.COMPILE /COMPILE GLXINI.MAC
.COMPILE /COMPILE GLXCOM.MAC
.COMPILE /COMPILE GLXFIL.MAC
.COMPILE /COMPILE GLXFUN.MAC
.COMPILE /COMPILE GLXINT.MAC
.COMPILE /COMPILE GLXIPC.MAC
.COMPILE /COMPILE GLXKBD.MAC
.COMPILE /COMPILE GLXLNK.MAC
.COMPILE /COMPILE GLXMEM.MAC
.COMPILE /COMPILE GLXOTS.MAC
.COMPILE /COMPILE GLXSCN.MAC
.COMPILE /COMPILE GLXTXT.MAC
.COMPILE /COMPILE GLXUTL.MAC

LOAD::
.R LINK
*GLXLIB /SSAVE = -
*/SET:.HIGH.:624000 /SET:DATA:674000 /SYMSEG:PSECT:.HIGH. /LOCALS -
*GLXMAC, GLXOTS, GLXCOM, GLXIPC, GLXFIL, GLXFUN, GLXKBD, -
*GLXLNK, GLXMEM, GLXSCN, GLXTXT, GLXUTL, GLXINT -
*/GO

;NOW CHECK IF WE CAN DO THE BLISSABLES; IF NOT, CONTINUE

.ERROR %

.DIRECT SYS:MONINT.EXE
.IF (ERROR) .GOTO FINI
.DIRECT SYS:BLISS.EXE
.IF (ERROR) .GOTO FINI
.ERROR ?

.R MONINT
*GLXMAC
.R BLISS
*GLXMAC=GLXMAC/LIBRARY

FINI::

.ERROR ?

.DIRECT/CHECK GLXLIB.EXE,GLXLIB.REL
.PLEASE	GLXLIB Assembly Successful
.NOERROR
.SUBMIT GALAXY=/MOD/DEP:-1

%CERR::
%ERR::
.PLEASE	Error During GLXLIB Assembly
%FIN::

