;[NEBULA.CTL]
;
; This control file will build the GALAXY Network Queue Controller
; for a DECsystem-10.
;
; Sources:	NEBPRM.MAC	NEBULA.MAC
;		NEBANF.MAC	NEBDCN.MAC
;
; Input:	ACTSYM.UNV	GLXLIB.REL	GLXMAC.UNV	ORNMAC.UNV
;		QSRMAC.UNV	UUOSYM.UNV
;
; Output:	NEBULA.EXE
TOPS10::
.SET WATCH VERSION
.ASSIGN DEC SYS
.ASSIGN DEC REL
.ASSIGN DEC UNV

.DIRECT /CHECK /SLOW NEBPRM.MAC,NEBULA.MAC,NEBANF.MAC,NEBDCN.MAC

.COMPILE/COMPILE NEBPRM.MAC
.COMPILE/COMPILE NEBULA.MAC
;.COMPILE/COMPILE NEBANF.MAC
.COMPILE/COMPILE NEBDCN.MAC

.R LINK
*NEBULA/SAVE = /LOCALS /SYMSEG:LOW /SEGMENT:LOW NEBULA,-
*NEBDCN,-
;*NEBANF,-
*/GO

.DIRECT /CHECK /SLOW NEBULA.EXE

.PLEASE	NEBULA Assembly Successful
.NOERROR
.DEASSIGN SYS
.SUBMIT GALAXY = /MODIFY /DEPEND:-1
.GOTO END

%CERR:: .GOTO ERROR
%ERR::  .GOTO ERROR
%TERR:: .GOTO ERROR

ERROR:: .PLEASE Error during NEBSPL assembly

END::
%FIN::
;[End of NEBULA.CTL]
