	PARAMETER EQL=0,NEQ=1,GEQ=2,LEQ=3,GTR=4,LSS=5
	PARAMETER APPEND=1,NUMERI=4,PAD=8
	PARAMETER PADDED=0,IGNORE=1,EXACT=2,TRANSL=4,TRACE=8
	PARAMETER IDXEND=1,ANCHOR=2,PARTIA=4,MULTIP=8,WHICH=16
	PARAMETER BACKWA=8
	PARAMETER TOASCI=1,BOUNDS=2,YESBOU=8
	PARAMETER ZEROPA=2,NOFILL=4,ALWAYS=8
